# Generated by Django 2.1.5 on 2023-02-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
