# Generated by Django 2.1.5 on 2023-03-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0003_userprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_friend', to='musicial.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='musicial.UserProfile')),
            ],
        ),
    ]
