# Generated by Django 2.1.5 on 2023-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0004_friendprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendprofile',
            name='friend',
        ),
        migrations.AddField(
            model_name='friendprofile',
            name='friend',
            field=models.ManyToManyField(related_name='target_friend', to='musicial.UserProfile'),
        ),
    ]
