# Generated by Django 2.1.5 on 2023-03-12 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0011_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 12, 12, 56, 28, 187476)),
        ),
    ]
