# Generated by Django 2.1.5 on 2023-03-16 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0015_auto_20230316_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 20, 43, 56, 912574)),
        ),
    ]
