# Generated by Django 2.1.5 on 2023-03-18 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0016_auto_20230316_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlistid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songid', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('artist', models.CharField(blank=True, max_length=512)),
                ('music_url', models.URLField(blank=True, max_length=600)),
                ('image_url', models.URLField(blank=True, max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 18, 14, 36, 13, 817363)),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlist_songs', to='musicial.Song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to='musicial.UserProfile'),
        ),
    ]
