# Generated by Django 2.1.5 on 2023-03-18 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0017_auto_20230318_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 18, 16, 48, 39, 805204)),
        ),
    ]
