# Generated by Django 2.1.5 on 2023-03-22 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0019_auto_20230320_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 11, 30, 59, 603472)),
        ),
    ]
