# Generated by Django 2.1.5 on 2023-03-22 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0020_auto_20230322_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 12, 3, 29, 875204)),
        ),
    ]
