# Generated by Django 2.1.5 on 2023-03-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0007_auto_20230304_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='target_user', serialize=False, to='musicial.UserProfile'),
        ),
    ]
