# Generated by Django 2.1.5 on 2023-03-12 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0009_auto_20230304_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='posts')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField(default='Sun, Mar 12, 2023')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='musicial.UserProfile')),
            ],
        ),
    ]
