# Generated by Django 2.1.5 on 2023-03-17 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0016_auto_20230316_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 20, 21, 19, 684794)),
        ),
    ]
