# Generated by Django 2.1.5 on 2023-03-17 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicial', '0017_auto_20230317_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 20, 25, 5, 954253)),
        ),
    ]
